import = [
	"/Users/darkrai/Projects/dotfiles/alacritty/catppuccin/catppuccin-macchiato.yml",
]

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#5c5c5c"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#a6bc69"
magenta = "#c594c5"
red = "#e57373"
white = "#f3f4f5"
yellow = "#fac863"

[colors.cursor]
cursor = "#c0c5ce"
text = "#212121"

[colors.normal]
black = "#212121"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#a6bc69"
magenta = "#c594c5"
red = "#e57373"
white = "#c0c5ce"
yellow = "#fac863"

[colors.primary]
background = "#212121"
bright_foreground = "#f3f4f5"
foreground = "#c0c5ce"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "ZedMono Nerd Font"
# family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font"
# family = "MonaspiceNe Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font"
# family = "MonaspiceNe Nerd Font"
style = "Medium Italic"

[font.normal]
family = "ZedMono Nerd Font"
# family = "MonaspiceNe Nerd Font"
style = "Medium"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
# auto_scroll = false
# faux_multiplier = 3
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "transparent"
dynamic_title = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 45

[window.padding]
x = 8
y = 2
